'use strict';

// tests for currentTime
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('test2', '/src/handler.js', 'test2');
const mongoUnit = require('mongo-unit')

describe('test2', () => {

    beforeEach(async () => {
        await mongoUnit.drop();
    });

    it('implement tests here', async () => {
        const response = await wrapped.run({});
        expect(response).to.not.be.empty;
    });

    it('implement tests here', async () => {
        const response = await wrapped.run({});
        expect(response).to.not.be.empty;
    });

});

