'use strict';

// tests for currentTime
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('test1', '/src/handler.js', 'test1');

describe('test1', () => {
    it('implement tests here', async () => {
        const response = await wrapped.run({});
        expect(response).to.not.be.empty;
    });

    it('implement tests here', async () => {
        const response = await wrapped.run({});
        expect(response).to.not.be.empty;
    });
});
